# Generated by Django 5.0.6 on 2024-06-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_name_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_non_blank_phone',
        ),
    ]
