# Generated by Django 5.0.6 on 2024-06-12 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('total_day', models.IntegerField()),
                ('total_night', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='trip/thumbnails/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.TextField()),
                ('meet_point', models.CharField(max_length=255)),
                ('trip_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('min_member', models.IntegerField()),
                ('max_member', models.IntegerField()),
                ('rate_avg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('regency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.regency')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='TripExclude',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excludes', to='trip.trip')),
            ],
            options={
                'db_table': 'trip_excludes',
            },
        ),
        migrations.CreateModel(
            name='TripInclude',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='trip.trip')),
            ],
            options={
                'db_table': 'trip_includes',
            },
        ),
        migrations.CreateModel(
            name='TripItinerary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('description', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trip.trip')),
            ],
            options={
                'db_table': 'trip_itineraries',
            },
        ),
    ]
