# Generated by Django 5.0.6 on 2024-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_tripexclude_tripinclude_tripitinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='rate_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
