# Generated by Django 5.0.6 on 2024-06-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_rate_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='trip/thumbnails/'),
        ),
    ]
