# Generated by Django 5.0.6 on 2024-06-18 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_trip_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripexclude',
            old_name='description',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='tripinclude',
            old_name='description',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='tripitinerary',
            old_name='description',
            new_name='activity',
        ),
        migrations.AlterField(
            model_name='tripexclude',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_excludes', to='trip.trip'),
        ),
        migrations.AlterField(
            model_name='tripinclude',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_includes', to='trip.trip'),
        ),
        migrations.AlterField(
            model_name='tripitinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_itineraries', to='trip.trip'),
        ),
    ]
