# Generated by Django 5.0.6 on 2024-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_remove_tripitinerary_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitinerary',
            name='activities',
            field=models.JSONField(default=dict),
        ),
    ]
