# Generated by Django 5.0.6 on 2024-06-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_remove_tripitinerary_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitinerary',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
