# Generated by Django 5.0.6 on 2024-06-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_alter_tripitinerary_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitinerary',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
