# Generated by Django 5.0.6 on 2024-06-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_alter_tripitinerary_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
