# Generated by Django 5.0.6 on 2024-07-18 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '__first__'),
        ('trip', '0012_alter_trip_options_alter_tripexclude_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('cancel', 'Cancel'), ('fail', 'Fail'), ('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('order_number', models.CharField(max_length=25)),
                ('trip_date', models.DateField(null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trip.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('payment_number', models.CharField(max_length=25)),
                ('proof_date', models.DateField(null=True)),
                ('proof_image', models.ImageField(upload_to='order/payment_proofs/')),
                ('status', models.CharField(choices=[('cancel', 'Cancel'), ('fail', 'Fail'), ('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='general.bank')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.order')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['created_at'],
            },
        ),
    ]
