# Generated by Django 5.0.6 on 2024-07-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('fail', 'Fail'), ('success', 'Success')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('fail', 'Fail'), ('success', 'Success')], default='pending', max_length=20),
        ),
    ]
