# Generated by Django 5.0.6 on 2024-07-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('fail', 'Fail'), ('cancel', 'Cancel'), ('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('fail', 'Fail'), ('cancel', 'Cancel'), ('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
