# Generated by Django 5.0.6 on 2024-11-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('fail', 'Fail'), ('pending', 'Pending'), ('success', 'Success'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('fail', 'Fail'), ('pending', 'Pending'), ('success', 'Success'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
    ]
